AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ordersapi

  Sample SAM Template for ordersapi

Resources:
  CreateOrderFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ordersapi
      Handler: com.thanthu.labmda.api.CreateOrderLambda::createOrder
      Runtime: java11
      MemorySize: 512
      Events:
        OrderEvents:
            Type: Api
            Properties:
                Path: /orders
                Method: POST
  ReadOrdersFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ordersapi
      Handler: com.thanthu.labmda.api.ReadOrdersLambda::getOrders
      Runtime: java11
      MemorySize: 512
      Events:
        OrderEvents:
            Type: Api
            Properties:
                Path: /orders
                Method: GET