AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ordersapi

  Sample SAM Template for ordersapi
  
Globals:
  Function:
    Runtime: java11
    MemorySize: 512
    Timeout: 30
    Environment:
      Variables:
        ORDERS_TABLE: !Ref OrdersTable    

Resources:
  OrdersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
  CreateOrderFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ordersapi
      Handler: com.thanthu.labmda.api.CreateOrderLambda::createOrder
      Events:
        OrderEvents:
            Type: Api
            Properties:
                Path: /orders
                Method: POST
  ReadOrdersFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ordersapi
      Handler: com.thanthu.labmda.api.ReadOrdersLambda::getOrders
      Events:
        OrderEvents:
            Type: Api
            Properties:
                Path: /orders
                Method: GET