AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ordersapi

  Sample SAM Template for ordersapi

Resources:
  CreateOrderFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: CreateOrderFunction
      Handler: helloworld.App::handleRequest
      Runtime: java11
      MemorySize: 512